import type { SubscriptionPlan } from './types'

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-001',
    code: 'INT-LITE-25',
    name: 'AN Lite-Net 25mbps',
    categoryId: 'category-internet',
    category: 'Internet',
    billingType: 'Prepaid',
    speed: '25 Mbps',
    channels: '-',
    price: 699,
    subscribers: 24,
    status: 'Active',
    updatedAt: 'May 4, 2026',
  },
  {
    id: 'plan-002',
    code: 'INT-NEW-100-999',
    name: 'AN NEW 100mbps 999',
    categoryId: 'category-internet',
    category: 'Internet',
    billingType: 'Prepaid',
    speed: '100 Mbps',
    channels: '-',
    price: 999,
    subscribers: 5,
    status: 'Active',
    updatedAt: 'May 4, 2026',
  },
  {
    id: 'plan-003',
    code: 'CAB-PRIME-60',
    name: 'Access Prime',
    categoryId: 'category-cable',
    category: 'Cable',
    billingType: 'Postpaid',
    speed: '-',
    channels: '60 channels',
    price: 450,
    subscribers: 12,
    status: 'Active',
    updatedAt: 'May 2, 2026',
  },
  {
    id: 'plan-004',
    code: 'CAB-PREM-75',
    name: 'Access Premium',
    categoryId: 'category-cable',
    category: 'Cable',
    billingType: 'Postpaid',
    speed: '-',
    channels: '75 channels',
    price: 550,
    subscribers: 10,
    status: 'Active',
    updatedAt: 'May 2, 2026',
  },
  {
    id: 'plan-005',
    code: 'COMBO-15M-UNLI-MAX-5',
    name: 'COMBO-15M-UNLI-MAX-5',
    categoryId: 'category-combo',
    category: 'Combo',
    billingType: 'Postpaid',
    speed: '15 Mbps',
    channels: 'Access Prime',
    price: 999,
    subscribers: 2,
    status: 'Draft',
    updatedAt: 'Apr 28, 2026',
  },
  {
    id: 'plan-006',
    code: 'EXT-TV',
    name: 'TV Extension',
    categoryId: 'category-extension',
    category: 'Extension',
    billingType: 'Prepaid',
    speed: '-',
    channels: 'Extension',
    price: 150,
    subscribers: 3,
    status: 'Archived',
    updatedAt: 'Apr 19, 2026',
  },
]
