import type { Installation } from './types'

export const installations: Installation[] = [
  {
    id: 'INS-001',
    accountNumber: '1234-121221-2121',
    name: 'John Doe',
    plan: 'Fiber 100 Mbps',
    city: 'Caloocan',
    barangay: 'Bagumbong',
    technician: 'Miguel Reyes',
    crew: 'North Fiber Team',
    scheduleDate: 'Jun 03, 2026',
    status: 'Scheduled',
    phoneNumber: '0917 482 1093',
    address: 'Block 12 Lot 8, Bagumbong, Caloocan',
    materials: 'ONU, router, 80m drop cable, 2 SC connectors',
    notes: 'Customer prefers morning schedule.',
  },
  {
    id: 'INS-002',
    accountNumber: '1234-121221-2122',
    name: 'Jane Smith',
    plan: 'Fiber 200 Mbps',
    city: 'Quezon City',
    barangay: 'Commonwealth',
    technician: 'Carlo Santos',
    crew: 'QC Install Crew',
    scheduleDate: 'Jun 03, 2026',
    status: 'In Progress',
    phoneNumber: '0928 115 7402',
    address: 'Unit 4B, Commonwealth Avenue, Quezon City',
    materials: 'ONU, router, 60m drop cable, 2 SC connectors',
    notes: 'Building admin approval already confirmed.',
  },
  {
    id: 'INS-003',
    accountNumber: '1234-121221-2123',
    name: 'Bob Johnson',
    plan: 'Basic 50 Mbps',
    city: 'Manila',
    barangay: 'Sampaloc',
    technician: 'Ramon Dela Cruz',
    crew: 'Manila Field Team',
    scheduleDate: 'Jun 04, 2026',
    status: 'Pending',
    phoneNumber: '0999 304 8816',
    address: '712 Sobriedad Street, Sampaloc, Manila',
    materials: 'ONU, router, 40m drop cable, 2 SC connectors',
    notes: 'Waiting for final customer confirmation.',
  },
  {
    id: 'INS-004',
    accountNumber: '1234-121221-2124',
    name: 'Alice Brown',
    plan: 'Fiber 100 Mbps',
    city: 'Valenzuela',
    barangay: 'Karuhatan',
    technician: 'Paolo Garcia',
    crew: 'Valenzuela Crew A',
    scheduleDate: 'Jun 04, 2026',
    status: 'Installed',
    phoneNumber: '0915 660 3371',
    address: '128 MacArthur Highway, Karuhatan, Valenzuela',
    materials: 'ONU, router, 90m drop cable, 2 SC connectors',
    notes: 'Activated and speed test passed.',
  },
  {
    id: 'INS-005',
    accountNumber: '1234-121221-2125',
    name: 'Charlie Wilson',
    plan: 'Fiber 300 Mbps',
    city: 'Malabon',
    barangay: 'Longos',
    technician: 'Luis Navarro',
    crew: 'North Fiber Team',
    scheduleDate: 'Jun 05, 2026',
    status: 'Scheduled',
    phoneNumber: '0936 918 4520',
    address: 'Lot 5, Longos, Malabon',
    materials: 'ONU, router, 110m drop cable, 2 SC connectors',
    notes: 'Bring ladder for second-floor cable route.',
  },
  {
    id: 'INS-006',
    accountNumber: '1234-121221-2126',
    name: 'Maria Santos',
    plan: 'Fiber 200 Mbps',
    city: 'Caloocan',
    barangay: 'Deparo',
    technician: 'Miguel Reyes',
    crew: 'North Fiber Team',
    scheduleDate: 'Jun 05, 2026',
    status: 'Failed',
    phoneNumber: '0918 227 6401',
    address: 'Phase 3, Deparo, Caloocan',
    materials: 'ONU, router, 70m drop cable, 2 SC connectors',
    notes: 'No available port at nearest NAP. Needs reassignment.',
  },
  {
    id: 'INS-007',
    accountNumber: '1234-121221-2127',
    name: 'Daniel Cruz',
    plan: 'Basic 50 Mbps',
    city: 'Navotas',
    barangay: 'San Roque',
    technician: 'Nico Ramos',
    crew: 'Coastal Crew',
    scheduleDate: 'Jun 06, 2026',
    status: 'Cancelled',
    phoneNumber: '0927 884 5109',
    address: 'San Roque, Navotas',
    materials: 'ONU, router, 50m drop cable, 2 SC connectors',
    notes: 'Customer requested cancellation.',
  },
  {
    id: 'INS-008',
    accountNumber: '1234-121221-2128',
    name: 'Patricia Lim',
    plan: 'Fiber 100 Mbps',
    city: 'Quezon City',
    barangay: 'Batasan Hills',
    technician: 'Carlo Santos',
    crew: 'QC Install Crew',
    scheduleDate: 'Jun 06, 2026',
    status: 'Pending',
    phoneNumber: '0995 711 2380',
    address: 'Batasan Hills, Quezon City',
    materials: 'ONU, router, 75m drop cable, 2 SC connectors',
    notes: 'Verify exact landmark before dispatch.',
  },
]
