import type { JobOrder } from './types'

export const problemCategories = [
  'No Internet',
  'Slow Connection',
  'LOS / Fiber Cut',
  'Router Issue',
  'Billing Concern',
  'Relocation',
  'Other',
] as const

export const jobOrderPriorities = ['Low', 'Medium', 'High', 'Urgent'] as const

export const technicians = [
  'Miguel Reyes',
  'Carlo Santos',
  'Ramon Dela Cruz',
  'Paolo Garcia',
  'Luis Navarro',
  'Nico Ramos',
] as const

export const jobOrders: JobOrder[] = [
  {
    id: '1',
    ticketNumber: 'JO-2026-0001',
    accountNumber: '1234-121221-2121',
    subscriberName: 'John Doe',
    phoneNumber: '0917 482 1093',
    plan: 'Fiber 100 Mbps',
    city: 'Caloocan',
    barangay: 'Bagumbong',
    problemCategory: 'No Internet',
    problemDetails: 'Customer reports no internet since last night. ONU power is on but LOS light is blinking red.',
    priority: 'High',
    technician: 'Miguel Reyes',
    status: 'Assigned',
    createdDate: 'May 30, 2026',
    lastUpdate: 'Assigned to field technician for line checking.',
    activities: [
      {
        id: 'JO-2026-0001-A1',
        title: 'Created ticket',
        description: 'No internet issue logged by operations desk.',
        timestamp: 'May 30, 2026 08:20 AM',
      },
      {
        id: 'JO-2026-0001-A2',
        title: 'Assigned technician',
        description: 'Assigned to Miguel Reyes for field checking.',
        timestamp: 'May 30, 2026 08:35 AM',
      },
    ],
  },
  {
    id: '2',
    ticketNumber: 'JO-2026-0002',
    accountNumber: '1234-121221-2122',
    subscriberName: 'Jane Smith',
    phoneNumber: '0928 115 7402',
    plan: 'Fiber 200 Mbps',
    city: 'Quezon City',
    barangay: 'Commonwealth',
    problemCategory: 'Slow Connection',
    problemDetails: 'Speed test is below 20 Mbps during peak hours. Customer already restarted router.',
    priority: 'Medium',
    technician: 'Carlo Santos',
    status: 'In Progress',
    createdDate: 'May 30, 2026',
    lastUpdate: 'Checking NAP utilization and customer router signal levels.',
    activities: [
      {
        id: 'JO-2026-0002-A1',
        title: 'Created ticket',
        description: 'Slow connection complaint recorded.',
        timestamp: 'May 30, 2026 09:10 AM',
      },
      {
        id: 'JO-2026-0002-A2',
        title: 'Assigned technician',
        description: 'Assigned to Carlo Santos.',
        timestamp: 'May 30, 2026 09:22 AM',
      },
      {
        id: 'JO-2026-0002-A3',
        title: 'Status changed',
        description: 'Moved from Assigned to In Progress.',
        timestamp: 'May 30, 2026 10:05 AM',
      },
    ],
  },
  {
    id: '3',
    ticketNumber: 'JO-2026-0003',
    accountNumber: '1234-121221-2123',
    subscriberName: 'Bob Johnson',
    phoneNumber: '0999 304 8816',
    plan: 'Basic 50 Mbps',
    city: 'Manila',
    barangay: 'Sampaloc',
    problemCategory: 'Router Issue',
    problemDetails: 'Wi-Fi drops every few minutes. LAN connection remains stable.',
    priority: 'Low',
    technician: 'Ramon Dela Cruz',
    status: 'Open',
    createdDate: 'May 29, 2026',
    lastUpdate: 'Waiting for technician assignment confirmation.',
    activities: [
      {
        id: 'JO-2026-0003-A1',
        title: 'Created ticket',
        description: 'Router issue logged by customer support.',
        timestamp: 'May 29, 2026 04:45 PM',
      },
    ],
  },
  {
    id: '4',
    ticketNumber: 'JO-2026-0004',
    accountNumber: '1234-121221-2124',
    subscriberName: 'Alice Brown',
    phoneNumber: '0915 660 3371',
    plan: 'Fiber 100 Mbps',
    city: 'Valenzuela',
    barangay: 'Karuhatan',
    problemCategory: 'LOS / Fiber Cut',
    problemDetails: 'Possible fiber cut after road work near the service address.',
    priority: 'Urgent',
    technician: 'Paolo Garcia',
    status: 'Resolved',
    createdDate: 'May 29, 2026',
    lastUpdate: 'Drop cable replaced and connection restored.',
    activities: [
      {
        id: 'JO-2026-0004-A1',
        title: 'Created ticket',
        description: 'Possible fiber cut reported after road work.',
        timestamp: 'May 29, 2026 07:50 AM',
      },
      {
        id: 'JO-2026-0004-A2',
        title: 'Assigned technician',
        description: 'Assigned to Paolo Garcia.',
        timestamp: 'May 29, 2026 08:05 AM',
      },
      {
        id: 'JO-2026-0004-A3',
        title: 'Resolved',
        description: 'Drop cable replaced and service restored.',
        timestamp: 'May 29, 2026 11:40 AM',
      },
    ],
  },
  {
    id: '5',
    ticketNumber: 'JO-2026-0005',
    accountNumber: '1234-121221-2125',
    subscriberName: 'Charlie Wilson',
    phoneNumber: '0936 918 4520',
    plan: 'Fiber 300 Mbps',
    city: 'Malabon',
    barangay: 'Longos',
    problemCategory: 'Billing Concern',
    problemDetails: 'Subscriber says account was paid but portal still shows overdue balance.',
    priority: 'Medium',
    technician: 'Luis Navarro',
    status: 'Closed',
    createdDate: 'May 28, 2026',
    lastUpdate: 'Payment posted and subscriber notified.',
    activities: [
      {
        id: 'JO-2026-0005-A1',
        title: 'Created ticket',
        description: 'Billing concern submitted by subscriber.',
        timestamp: 'May 28, 2026 01:15 PM',
      },
      {
        id: 'JO-2026-0005-A2',
        title: 'Resolved',
        description: 'Payment posted to the subscriber account.',
        timestamp: 'May 28, 2026 02:30 PM',
      },
      {
        id: 'JO-2026-0005-A3',
        title: 'Closed',
        description: 'Subscriber notified and ticket closed.',
        timestamp: 'May 28, 2026 03:00 PM',
      },
    ],
  },
  {
    id: '6',
    ticketNumber: 'JO-2026-0006',
    accountNumber: '1234-121221-2126',
    subscriberName: 'Maria Santos',
    phoneNumber: '0918 227 6401',
    plan: 'Fiber 200 Mbps',
    city: 'Caloocan',
    barangay: 'Deparo',
    problemCategory: 'Relocation',
    problemDetails: 'Customer requested transfer to another unit in the same subdivision.',
    priority: 'Low',
    technician: 'Nico Ramos',
    status: 'Cancelled',
    createdDate: 'May 27, 2026',
    lastUpdate: 'Customer cancelled relocation request.',
    activities: [
      {
        id: 'JO-2026-0006-A1',
        title: 'Created ticket',
        description: 'Relocation request created.',
        timestamp: 'May 27, 2026 10:00 AM',
      },
      {
        id: 'JO-2026-0006-A2',
        title: 'Cancelled',
        description: 'Customer cancelled the relocation request.',
        timestamp: 'May 27, 2026 02:20 PM',
      },
    ],
  },
  {
    id: '7',
    ticketNumber: 'JO-2026-0007',
    accountNumber: '1234-121221-2128',
    subscriberName: 'Patricia Lim',
    phoneNumber: '0995 711 2380',
    plan: 'Fiber 100 Mbps',
    city: 'Quezon City',
    barangay: 'Batasan Hills',
    problemCategory: 'No Internet',
    problemDetails: 'Connection is down after heavy rain. Customer cannot access modem admin page.',
    priority: 'High',
    technician: 'Carlo Santos',
    status: 'Assigned',
    createdDate: 'May 30, 2026',
    lastUpdate: 'Scheduled for same-day field visit.',
    activities: [
      {
        id: 'JO-2026-0007-A1',
        title: 'Created ticket',
        description: 'No internet issue logged after heavy rain.',
        timestamp: 'May 30, 2026 07:30 AM',
      },
      {
        id: 'JO-2026-0007-A2',
        title: 'Assigned technician',
        description: 'Assigned to Carlo Santos for same-day visit.',
        timestamp: 'May 30, 2026 07:45 AM',
      },
    ],
  },
  {
    id: '8',
    ticketNumber: 'JO-2026-0008',
    accountNumber: '1234-121221-2130',
    subscriberName: 'Sofia Reyes',
    phoneNumber: '0916 490 3305',
    plan: 'Fiber 200 Mbps',
    city: 'Valenzuela',
    barangay: 'Marulas',
    problemCategory: 'Other',
    problemDetails: 'Customer requests on-site check before upgrading plan.',
    priority: 'Low',
    technician: 'Miguel Reyes',
    status: 'Open',
    createdDate: 'May 30, 2026',
    lastUpdate: 'Ticket created by operations desk.',
    activities: [
      {
        id: 'JO-2026-0008-A1',
        title: 'Created ticket',
        description: 'On-site check request recorded before plan upgrade.',
        timestamp: 'May 30, 2026 11:05 AM',
      },
    ],
  },
]
